trigger:
  branches:
    include:
    - main
    - v*
  paths:
    exclude:
    - doc/
    - '*.md'

variables:
  TreatWarningsAsErrors: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

jobs:
  - template: azure-pipelines/build.yml